WITH raw_data AS (
    SELECT 'ed53639d-e9d5-45f8-939f-704ebafe267a' AS user_id, [CURRENT_TIMESTAMP(), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY)] AS timestamps
    UNION ALL SELECT '5ecb6274-3f50-4a08-9e43-3e7ae450b6ce' AS user_id, [TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 4 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 5 DAY)] AS timestamps
    UNION ALL SELECT '1f0d087b-db9e-4544-ab24-8d43635f8337' AS user_id, [TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 4 DAY)] AS timestamps,
    UNION ALL SELECT '784fc6e1-ec8e-4792-aad7-d566c07b1538' AS user_id, [TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 3 DAY), TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 4 DAY)] AS timestamps
), user_login AS (
    SELECT user_id, login_time
    FROM raw_data rd
    CROSS JOIN UNNEST(rd.timestamps) AS login_time
)
SELECT * FROM user_login
